
services:
  doctor-service:
    build:
      context: ./doctor
    container_name: doctor-service
    ports:
      - "8002:8002"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/doctor
    depends_on:
      - mongodb

  patient-service:
    build:
      context: ./patient
    container_name: patient-service
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/patient
    depends_on:
      - mongodb


  notification-service:
    build:
      context: ./notification
    container_name: notification-service
    ports:
      - "8004:8004"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/notification
    depends_on:
      - mongodb

  appointment-service:
    build:
      context: ./appointment
    container_name: appointment-service
    ports:
      - "8003:8003"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/appointment
    depends_on:
      - mongodb

  gateway:
    build:
      context: ./gateway
    container_name: gateway
    ports:
      - "8000:8000"
    depends_on:
      - patient-service
      - doctor-service
      - notification-service
      - appointment-service


  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
